# Generated by Django 5.1.2 on 2025-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_role_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='KQbGADOTLjzkAUkVn55FYZNVcVMtI227rm6BSo2C4BUjDiMNZouVvY8c6cogygXy', max_length=64, unique=True),
        ),
    ]
