# Generated by Django 5.1.2 on 2025-01-14 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_interviewer_token_employerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='tTdCGGayaaCleX8eKXRYpaHxsw6KrM60EzkdBuKHLqzrRMHMdKg48aEXNc51TxzQ', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='api.jobapplication')),
                ('interviewers', models.ManyToManyField(related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
