# Generated by Django 5.1.2 on 2025-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_interviewer_token_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='calendar_event_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='vGor2FXiJgKgFxLaY8SesDa5ljhJPDMyacsOd6uFvACdELS5md9MMfIyPvphK3zr', max_length=64, unique=True),
        ),
    ]
