# Generated by Django 5.1.2 on 2025-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interview_calendar_event_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='calendar_event_link',
        ),
        migrations.AddField(
            model_name='interview',
            name='event_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(related_name='interviews', to='api.interviewer'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='L9OpUTmaz6dJlTyOdQUipAZdltA6s4VUZ7C2HfQtVmO01nREDWTA3GclYioRXr2T', max_length=64, unique=True),
        ),
    ]
