# Generated by Django 5.1.2 on 2025-01-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_interview_calendar_event_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='8i2a2a7o547XjUzRtaVgbDvYjry28Jim1dshtlwwpAuGuGU1LvvIX8Iv3extXIIX', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField()),
                ('candidate_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobapplication')),
                ('interviewers', models.ManyToManyField(to='api.interviewer')),
            ],
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
