# Generated by Django 5.1.2 on 2025-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_interviewer_token_interviewinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='0FJHqLXvHQ002WdHQJhF8HSrdBdufwYUphUyOBC2AKGYhwJlC5bcgYld6kmaE3I6', max_length=64, unique=True),
        ),
    ]
