# Generated by Django 5.1.2 on 2025-01-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_jobapplication_interview_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='Tn6DoZZoIicjCHY1Ks9OAnJr8WbVkxhGfjF5TP02qWt9F6EBkynNtMYngx5uVc9S', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.interviewinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
