# Generated by Django 5.1.2 on 2025-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_note_updated_at_alter_interviewer_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='app_password',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default='NetVision', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='qRd4Szua0bm5ASG0OGAPpF4pH9YDKiKQQ239xPhBTXmnQllIewCzhXGSgHWg3lF3', max_length=64, unique=True),
        ),
    ]
