# Generated by Django 5.1.2 on 2025-01-30 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_interviewer_token_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='bihmQAi6aKE6rWuKpINyWtoJwh8Dtfv9Dty16IPDCjqLfHVBWp6rUrhuXxvrTl37', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
