# Generated by Django 5.1.2 on 2025-01-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_interviewer_token_interviewerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewerprofile',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='qWUYUoLW14luwJzgf5I6CIndwTpQ06p6XelGQZ8627Z3Mmfc4tB49M8QagHYPCXe', max_length=64, unique=True),
        ),
    ]
