# Generated by Django 5.1.2 on 2025-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_interviewerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='company_name',
            field=models.CharField(default='NetVision', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='0wyVKK90bKq8hkVlYaPU4BgpVGNSIF6Kn1t5hQRORqDu8zRrhvqKBVwP0hgssU7t', max_length=64, unique=True),
        ),
    ]
