# Generated by Django 5.1.2 on 2025-01-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_interviewerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='xcGqw4tdFjobwGfpBcDwiUirK7oPTBgRSt2woilCjDcLNAckIybDlimdCkvo9Pp2', max_length=64, unique=True),
        ),
    ]
