# Generated by Django 5.1.2 on 2025-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_interviewinvitation_event_id_alter_interviewer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='E7rk2Zxs8crkDuV7iDLYp4moEWnrvrzeO58I1lCw4j8CZjVLKmWBmnoqc4sMbdXF', max_length=64, unique=True),
        ),
    ]
