# Generated by Django 5.1.2 on 2025-02-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_interviewer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='5yHCJPUoILbc4qp7fHiITsb46xM142ibmsU5AIKjUHIZHJCnbIU2eNFka3XKK359', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='api.jobapplication'),
        ),
    ]
