# Generated by Django 5.1.2 on 2025-02-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_interviewer_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='4P722eO1KnH5G0nioyL18BJfOvYt8pPj6LOEaFMugibww4NljEmGhitgkpb44Ten', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobapplication'),
        ),
    ]
