# Generated by Django 5.1.2 on 2025-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_interviewer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='BKtheSIfpSQGvFiToI7GqOi1F3d1UIn4L785HYMgraMIKbcSt00fMNCBpcckSmWb', max_length=64, unique=True),
        ),
    ]
