# Generated by Django 5.1.2 on 2025-02-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_interviewer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='jl09TljS9F4uPRwfZC5FHMFyuYromC3G7wl3ifnLQGIo9VvbWeC53IgnMTr9rk6D', max_length=64, unique=True),
        ),
    ]
