# Generated by Django 5.1.2 on 2025-02-18 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_jobapplication_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewinvitation',
            options={'ordering': ['-posted_date'], 'verbose_name': 'InterviewInvitation', 'verbose_name_plural': 'InterviewInvitation'},
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='token',
            field=models.CharField(default='ekTVNkKYLZXxFVUot9kjpJOQjcCpY88kO3S697g5jj1Oo7CKrLtu46i3tZPCAtxI', max_length=64, unique=True),
        ),
    ]
